#
# TP03 : Ajout d'une nouvelle entrée dans le menu gnu/linux
#
# EUROGICIEL Rennes - Formation noyau & drivers sous gnu/linux
#





# Modifiez le Makefile d'un autre drivers ; pour ce faire allez voir comment sont écris les Makefile d'autres répertoires.





#
# END OF FILE
#
